const admin = require('firebase-admin');
const path = require('path');

// Try to load the service account key
// NOTE: You MUST download this from Firebase Console and place it in E:\Raagam-be\serviceAccountKey.json
const serviceAccountPath = path.join(__dirname, '../../serviceAccountKey.json');

try {
    const b64 = "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQytYazJnb2tjd0tIZEMKb3MvanFQVEEvMlIxc0hHYjZmT21MWXd1SGoycC8wQ0U0NnY1TnRlRmRXVlNhYnFDOEY0UTRWSVZUVjRoSUo5ZwoyOHRiK014VHdkZ2grQ0dHMmpMSVNRU3I5SWdCQWNNdUhEM2JiNzkyZ2JxbWxHY0tTWmFaZkFGUkFMSE5NM1BDClV0Y1FXSm5wYVozcUNBcmVUaGIzL3ZuNkp3RXV3V0tmSGxYWjFBVCs4Si9CZUkvVFNiWEF6Y0lrYUdidzFlK0IKZmVQbGkwdmZLL2ZoLzRDM3dvKzRJS1o1bmJIOU5WT0hVSWF4b0xVNmNHanh6VEgyVWR6TE8rNWdtT2JKS1V3SQpNQUlBNXl1aVhHc0Z4UlN6UHQ5ajQ4K1BheDJaTzNTc2QyTXVYclNvd3ptUHQ4bEo3Y3ZmeUV6RTkxNENoVy9vCjlWWDdBRHMxQWdNQkFBRUNnZ0VBQXVJY3cwYXJpQ2FYOHdVRmRXL2JkcnphdE56UXE2K3BPYWFBOUFYYzFOU0IKZUVISnRHbVZvTjJpNndZR2hiNWZjWTJiU3R1MEgzZnNhNlFpTFZ3NnR6ZWp5SlM2RzZyMTlsY0RMVTBuQjhnUwoyaHRWWlU3Vnh1NjIzekhRbk9oR2EzTjk5WnkzUitIQkJCVnhoQWgydEU0ZHpzVnBuTHBYUUxlRFVJalA1bCtQCmpMSXhQamk1K3FXSWpMYWFIcEMwWis4NE5RNUF5dlRhS3lMRU5rUnVFbU1LNVRSRytOQng1eFlHSEZRNjJwUUoKMmxubUhKQkUrV1E2TG5Td1EraC9SQXNVZHcrUXdLN2kyUm4yVmlTcU0wbFNuSFdFUUxwbUxFa2xGTU9GdWhLTgpkRjA2YUFvK1ZLRWxOOEM3VDVySExVNyt3ZksvMElTVnM1MVpGU3I3UVFLQmdRRHB6RnI3SkRoWHpQK0ttQ0N2CjFTZmFDN3lEM0xtRmR5dzJmVXdLOGt0WmR3Syt3VjN1VGtEUHpBb1g4bEFKWUUvdjhuanBSUDd1cHdiWERCVUYKZyszRDUrWjd5dVdSalhQU1VmQVpvNWV2RWFCMGxwVnUwL1VoNmJoeks2MmcyTzd1c09zZFQzM09jaXcwREw5QgpTRlB6VitRN3FQQ0pxcXRFVXJDaEFsem14UUtCZ1FEUWNpcGc4bnQ5U0ZuTFl6cjdGTitpZmpxNjRjc3Z4aGh2CnVNeU44UktTR1hnc2JTSkdRUUxHNTA5WlhDVVJlZk9RMzNFYkhPUTZubk5UYVJSNVFMbyswT0dybVF1aktTRWsKNmpDVUFFN3ZDYWxlT0s3Unp1eFo1eFJkTDlrY21xemxsY0dEU1c3MmZvYmRRS1pZWEhjSWJZb3h4bm9GWVVxMwpiTlhpWW9USnNRS0JnQlNoWXJuY2hWaENENTZVTS9Zd0VmY3NwL0xlekVRWnN2NFA2bURnNW9NN2ZET0c3cG56CnI4Wm1VOUd2SVI3aXI4c1ZrMVBLTWRDdlRtdzFkYmxwM2RZMnBXRHhFM2JYaTR2WWpSNUdFRUZ6aGJ3aitZV3gKRUdWd3NVVUFhcTdSMWF1Y1V2TGdLOUxHd2wzSmJpcjlqZUxnTTVTTUlNV1ZHTTNMbWlockEvV2RBb0dBYTdyRgpXa3VZTlJ6Q2c5SnFOa0FJZ01PNmVNR2ZzTFl5QlBPK2pKR09ab0hSVVN5cUxTTUdXMlJLNTBVdlIwUCs5TjMyClordmJyTXdka0h0YmdIdEtocEtRUDQ2ZXJCbmlybUIyOE5iajlMaktsdzYyazJyZFRtMldZYjhMOTdPZExoN2kKMzRhQldkWDB2NzdjK2dmMzRSd3o4eHZBRHEzRTN0M2FBT0duL1ZFQ2dZRUFoQUhROW5SNmVPK1hXa3MxWktTZgpuVllhSml5dkhTK05oQSswNUx3MVQ2NWhEakV4UStPbDRNa1hnUEVLa2dneEJWT3IzQ2svNHhhWTRNQUtGeFNpCjhWclhGWE5KVWI5dTFsbThBZjBkTmFOeE5US2Z5c2g0SHhzZXVnbHBjV2xKRnRuV1ozaGZHV2ZDTzZTUENoVnMKOWc3clpQQURacVhqd1oxVkR6MldUdW89Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K";
    const serviceAccount = {
        projectId: "raagam-msc",
        clientEmail: "firebase-adminsdk-fbsvc@raagam-msc.iam.gserviceaccount.com",
        privateKey: Buffer.from(b64, 'base64').toString('utf8')
    };
    
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
    });
    console.log("Firebase Admin initialized successfully.");
} catch (err) {
    console.error("Firebase Admin initialization FAILED. Please ensure 'serviceAccountKey.json' exists or FIREBASE_CREDENTIALS is set.", err.message);
}

const db = admin.firestore();
const auth = admin.auth();

module.exports = { db, auth };
